server:
  port: 8001

spring:
  application:
    name: order

PRODUCT:
  ribbon:
    #请求链接超时时间
    ConnectTimeout: 2000
    #请求处理超时时间
    readTimeout: 15000
    #对所有操作都进行重试
    OkToRetryOnAllOperatins: true
    MaxAutoRetries: 1 #对当前选择的实例重试次数，不包括第一次
    MaxAutoRetriesNextServer: 1 #切换的重试次数
